export const POKEMON_REQUEST = 'POKEMON_REQUEST';
export const POKEMON_FAILURE = 'POKEMON_FAILURE';
export const ADD_ALL_POKEMONS = 'ADD_ALL_POKEMONS';
// export const UPDATE_FILTER = 'UPDATE_FILTER';
// export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_SELECTED_POKEMON = 'UPDATE_SELECTED_POKEMON';
