export const PLANT_REQUEST = 'PLANT_REQUEST';
export const PLANT_FAILURE = 'PLANT_FAILURE';
export const PLANT_SUCCESS = 'PLANT_SUCCESS';
export const ADD_ALL_PLANTS = 'ADD_ALL_PLANTS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
