import { createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
// import logger from 'redux-logger';
import thunk from 'redux-thunk';

import rootReducer from './rootReducer';

export const initialState = {
  plant: {
    loading: false,
    initialized: true,
    filter: 'All',
    filterInput: '',
    plants: [
      {
        id: 678281,
        common_name: 'Evergreen oak',
        slug: 'quercus-rotundifolia',
        scientific_name: 'Quercus rotundifolia',
        year: 1785,
        bibliography: 'Encycl. 1: 723 (1785)',
        author: 'Lam.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Beech family',
        genus_id: 5778,
        image_url: 'https://bs.floristic.org/image/o/1a03948baf0300da25558c2448f086d39b41ca30',
        synonyms: [
          'Quercus lyauteyi',
          'Quercus rotundifolia f. crassicupulata',
          'Quercus ballota',
          'Quercus ilex f. brevicupulata',
          'Quercus calycina',
          'Quercus rotundifolia f. dolichocalyx',
          'Quercus rotundifolia f. pilosella',
          'Quercus rotundifolia f. macrocarpa',
          'Quercus rotundifolia f. calycina',
          'Quercus ilex f. macrocarpa',
          'Quercus ilex subsp. ballota',
          'Quercus rotundifolia var. pilosella',
          'Quercus rotundifolia var. brevicupulata',
          'Quercus rotundifolia subsp. maghrebiana',
          'Quercus rotundifolia f. brevicupulata',
          'Quercus rotundifolia var. macrocarpa',
        ],
        genus: 'Quercus',
        family: 'Fagaceae',
        links: {
          self: '/api/v1/species/quercus-rotundifolia',
          plant: '/api/v1/plants/quercus-rotundifolia',
          genus: '/api/v1/genus/quercus',
        },
      },
      {
        id: 190500,
        common_name: 'Stinging nettle',
        slug: 'urtica-dioica',
        scientific_name: 'Urtica dioica',
        year: 1753,
        bibliography: 'Sp. Pl.: 984 (1753)',
        author: 'L.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Nettle family',
        genus_id: 1028,
        image_url: 'https://bs.floristic.org/image/o/85256a1c2c098e254fefe05040626a4df49ce248',
        synonyms: [
          'Urtica major',
          'Urtica tibetica',
          'Urtica sicula',
          'Urtica eckloniana',
          'Urtica haussknechtii',
          'Urtica submitis',
        ],
        genus: 'Urtica',
        family: 'Urticaceae',
        links: {
          self: '/api/v1/species/urtica-dioica',
          plant: '/api/v1/plants/urtica-dioica',
          genus: '/api/v1/genus/urtica',
        },
      },
      {
        id: 126957,
        common_name: 'Orchardgrass',
        slug: 'dactylis-glomerata',
        scientific_name: 'Dactylis glomerata',
        year: 1753,
        bibliography: 'Sp. Pl.: 71 (1753)',
        author: 'L.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Grass family',
        genus_id: 2284,
        image_url: 'https://bs.floristic.org/image/o/05c2f3cf28a921235daece7b31806741c7251784',
        synonyms: [
          'Koeleria dactylis',
          'Festuca glomerata',
          'Trachypoa vulgaris',
          'Phalaris glomerata',
          'Dactylis glomerata var. vivipara',
          'Dactylis glomerata var. detonsa',
          'Dactylis glomerata f. variegata',
          'Dactylis decalcata',
          'Dactylis abbreviata',
          'Dactylis glomerata f. hispida',
          'Dactylis stenophylla',
          'Dactylis kovarovicii',
          'Dactylis noeana',
          'Dactylis kirschbaumii',
          'Dactylis glomerata var. variegata',
          'Dactylis pubescens',
          'Festuca phalarioides',
          'Dactylis nemorosa',
          'Dactylis glaucescens',
          'Dactylis metlesicsii',
          'Dactylis altaica',
          'Dactylis glomerata var. titani',
          'Dactylis cylindracea',
          'Dactylis scaberrima',
          'Bromus cylindraceus',
          'Dactylis peylii',
          'Dactylis glomerata f. pubescens',
          'Dactylis capitellata',
          'Dactylis pendula',
          'Sesleria cirtensis',
          'Dactylis glomerata subsp. himalayensis',
        ],
        genus: 'Dactylis',
        family: 'Poaceae',
        links: {
          self: '/api/v1/species/dactylis-glomerata',
          plant: '/api/v1/plants/dactylis-glomerata',
          genus: '/api/v1/genus/dactylis',
        },
      },

    ],
    links: {
      first: '/api/v1/plants/search?page=1&q=hih',
      self: '"/api/v1/plants/search?q=hih"',
      last: '/api/v1/plants/search?page=24&q=hih',
    },
    error: '',
  },
  // filter: {
  //   filter: 'All',
  //   filterInput: '',
  // },

};

const store = createStore(
  rootReducer,
  initialState,
  composeWithDevTools(applyMiddleware(thunk)),
);

export default store;
