import { createStore, applyMiddleware } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
// import logger from 'redux-logger';
import thunk from 'redux-thunk';

import rootReducer from './rootReducer';

export const initialState = {
  plant: {
    loading: false,
    initialized: true,
    filter: 'All',
    filterInput: '',
    search: '',
    plants: [
      {
        id: 126322,
        common_name: 'Haspan flatsedge',
        slug: 'cyperus-haspan',
        scientific_name: 'Cyperus haspan',
        year: 1753,
        bibliography: 'Sp. Pl.: 45 (1753)',
        author: 'L.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Sedge family',
        genus_id: 10,
        image_url: 'https://bs.floristic.org/image/o/f27e1728204a23eeb8b75f673d91c755e34288be',
        synonyms: [
          'Cyperus cayennensis',
          'Cyperus haspan var. americanus',
          'Cyperus halpan L.',
          'Cyperus aphyllus',
          'Cyperus stellatus',
          'Cyperus triqueter',
          'Cyperus juncoides',
          'Cyperus nudus',
          'Cyperus americanus',
          'Cyperus princeae',
          'Cyperus adenophorus var. aphyllus',
          'Cyperus adenophorus',
          'Cyperus laticulmis',
          'Cyperus tunicatus',
          'Cyperus graminifolius',
          'Cyperus muehlenbergii',
          'Cyperus haspan var. amplissimus',
          'Cyperus haspan var. adenophorus',
          'Cyperus platyculmis',
          'Cyperus haspan var. riparius',
          'Cyperus haspan var. firmicaulis',
          'Cyperus haspan subsp. juncoides',
          'Cyperus haspan var. coarctatus',
          'Cyperus nudus var. firmior',
          'Cyperus nudus var. flaccidior',
          'Cyperus haspan f. major',
          'Cyperus junceus',
          'Cyperus cancellatus',
          'Cyperus efoliatus',
          'Cyperus leptos',
          'Cyperus phaeorhizus',
          'Cyperus planiculmis',
          'Cyperus pedatus',
          'Cyperus haspan f. coarctatus',
          'Cyperus microcarpus',
          'Cyperus riparius',
          'Cyperus cruciformis',
          'Cyperus vaginatus var. densiflorus',
          'Cyperus vaginatus var. contractus',
          'Cyperus vaginatus var. pseudotextilis',
          'Eucyperus gracilis',
          'Cyperus gracilis f. viviparus',
          'Cyperus gracilis',
          'Cyperus textilis',
          'Cyperus autumnalis',
          'Cyperus vaginatus',
          'Cyperus hyemalis',
          'Cyperus haspan var. dietrichiae',
          'Scirpus autumnalis',
          'Cyperus gramineus',
          'Cyperus halpan',
        ],
        genus: 'Cyperus',
        family: 'Cyperaceae',
        links: {
          self: '/api/v1/species/cyperus-haspan',
          plant: '/api/v1/plants/cyperus-haspan',
          genus: '/api/v1/genus/cyperus',
        },
      },
      {
        id: 167073,
        common_name: 'Maritime pine',
        slug: 'pinus-pinaster',
        scientific_name: 'Pinus pinaster',
        year: 1789,
        bibliography: 'Hort. Kew. 3: 367 (1789)',
        author: 'Aiton',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Pine family',
        genus_id: 5,
        image_url: 'https://bs.floristic.org/image/o/ac5c0cd692b6b87b468af909339bae3c84178963',
        synonyms: [
          'Pinus maritima',
          'Pinus glomerata',
          'Pinus pinaster subsp. acutisquama',
          'Pinus nigrescens',
          'Pinus syrtica',
          'Pinus detritis',
          'Pinus corteana',
          'Pinus neglecta',
          'Pinus sancta-helenica',
          'Pinus helenica',
          'Pinus scarina',
          'Pinus lemoniana',
          'Pinus nova-zelandica',
        ],
        genus: 'Pinus',
        family: 'Pinaceae',
        links: {
          self: '/api/v1/species/pinus-pinaster',
          plant: '/api/v1/plants/pinus-pinaster',
          genus: '/api/v1/genus/pinus',
        },
      },
      {
        id: 360452,
        common_name: 'Barroomplant',
        slug: 'aspidistra-elatior',
        scientific_name: 'Aspidistra elatior',
        year: 1834,
        bibliography: 'Tijdschr. Natuurl. Gesch. Physiol. 1: 76 (1834)',
        author: 'Blume',
        status: 'accepted',
        rank: 'species',
        family_common_name: null,
        genus_id: 10842,
        image_url: 'https://bs.floristic.org/image/o/9bd49be03c39e0dcbf261b71f8ce3a7256d74faa',
        synonyms: [
          'Aspidistra variegata',
          'Plectogyne variegata',
          'Aspidistra insularis',
        ],
        genus: 'Aspidistra',
        family: 'Asparagaceae',
        links: {
          self: '/api/v1/species/aspidistra-elatior',
          plant: '/api/v1/plants/aspidistra-elatior',
          genus: '/api/v1/genus/aspidistra',
        },
      },
      {
        id: 158935,
        common_name: 'Oleander',
        slug: 'nerium-oleander',
        scientific_name: 'Nerium indicum',
        year: 1753,
        bibliography: 'Sp. Pl.: 209 (1753)',
        author: 'L.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Dogbane family',
        genus_id: 2146,
        image_url: 'https://bs.floristic.org/image/o/70afcc5bc209fb74fa696e2888be8a22300c9d2e',
        synonyms: [
          'Nerium grandiflorum',
          'Nerium verecundum',
          'Nerium odoratum',
          'Nerium indicum',
          'Nerium odorum',
          'Nerium kotschyi',
          'Nerium latifolium',
          'Nerium splendens',
          'Nerium thyrsiflorum',
          'Nerium carneum',
          'Nerium flavescens',
          'Nerium mascatense',
          'Nerium lauriforme',
          'Nerium floridum',
          'Nerium luteum',
          'Oleander indica',
          'Oleander vulgaris',
          'Nerium japonicum',
          'Nerium odoratissimum',
          'Nerion oleandrum',
          'Nerium oleander subsp. kurdicum',
          'Nerium indicum subsp. kotschyi',
          'Nerium oleander var. indicum',
        ],
        genus: 'Nerium',
        family: 'Apocynaceae',
        links: {
          self: '/api/v1/species/nerium-oleander',
          plant: '/api/v1/plants/nerium-oleander',
          genus: '/api/v1/genus/nerium',
        },
      },
      {
        id: 375462,
        common_name: null,
        slug: 'hymenasplenium-hondoense',
        scientific_name: 'Hymenasplenium hondoense',
        year: 1992,
        bibliography: 'New Fl. Jap. Pterid.: 841 (1992)',
        author: '(N.Murak. & Hatan.) Nakaike',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Spleenwort family',
        genus_id: 10919,
        image_url: null,
        synonyms: [
          'Asplenium hondoense',
          'Asplenium unilaterale var. birii',
        ],
        genus: 'Hymenasplenium',
        family: 'Aspleniaceae',
        links: {
          self: '/api/v1/species/hymenasplenium-hondoense',
          plant: '/api/v1/plants/hymenasplenium-hondoense',
          genus: '/api/v1/genus/hymenasplenium',
        },
      },
      {
        id: 373550,
        common_name: null,
        slug: 'hymenasplenium-apogamum',
        scientific_name: 'Hymenasplenium apogamum',
        year: 1992,
        bibliography: 'New Fl. Jap. Pterid.: 841 (1992)',
        author: '(N.Murak. & Hatan.) Nakaike',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Spleenwort family',
        genus_id: 10919,
        image_url: null,
        synonyms: [
          'Asplenium unilaterale var. decurrens',
          'Asplenium apogamum',
        ],
        genus: 'Hymenasplenium',
        family: 'Aspleniaceae',
        links: {
          self: '/api/v1/species/hymenasplenium-apogamum',
          plant: '/api/v1/plants/hymenasplenium-apogamum',
          genus: '/api/v1/genus/hymenasplenium',
        },
      },
      {
        id: 655926,
        common_name: null,
        slug: 'diphysa-yucatanensis',
        scientific_name: 'Diphysa yucatanensis',
        year: 2009,
        bibliography: 'Revista Mex. Biodivers. 80: 288 (2009)',
        author: 'Hanan-Alipi & M.Sousa',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Pea family',
        genus_id: 2480,
        image_url: null,
        synonyms: [],
        genus: 'Diphysa',
        family: 'Fabaceae',
        links: {
          self: '/api/v1/species/diphysa-yucatanensis',
          plant: '/api/v1/plants/diphysa-yucatanensis',
          genus: '/api/v1/genus/diphysa',
        },
      },
      {
        id: 598135,
        common_name: null,
        slug: 'acidocroton-madrigalensis',
        scientific_name: 'Acidocroton madrigalensis',
        year: 2013,
        bibliography: 'Acta Bot. Mex. 104: 94 (2013)',
        author: 'Hanan-Alipi & V.W.Steinm.',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Spurge family',
        genus_id: 12646,
        image_url: null,
        synonyms: [],
        genus: 'Acidocroton',
        family: 'Euphorbiaceae',
        links: {
          self: '/api/v1/species/acidocroton-madrigalensis',
          plant: '/api/v1/plants/acidocroton-madrigalensis',
          genus: '/api/v1/genus/acidocroton',
        },
      },
      {
        id: 675145,
        common_name: null,
        slug: 'zapoteca-quichoi',
        scientific_name: 'Zapoteca quichoi',
        year: 1998,
        bibliography: 'Brittonia 50: 211 (1998)',
        author: 'H.M.Hern. & Hanan-Alipi',
        status: 'accepted',
        rank: 'species',
        family_common_name: 'Pea family',
        genus_id: 1285,
        image_url: null,
        synonyms: [],
        genus: 'Zapoteca',
        family: 'Fabaceae',
        links: {
          self: '/api/v1/species/zapoteca-quichoi',
          plant: '/api/v1/plants/zapoteca-quichoi',
          genus: '/api/v1/genus/zapoteca',
        },
      },
    ],
    chosen: {},
    links: {
      first: '/api/v1/plants/search?page=1&q=hih',
      self: '"/api/v1/plants/search?q=hih"',
      last: '/api/v1/plants/search?page=24&q=hih',
    },
    error: '',
  },
  // filter: {
  //   filter: 'All',
  //   filterInput: '',
  // },

};

const store = createStore(
  rootReducer,
  initialState,
  composeWithDevTools(applyMiddleware(thunk)),
);

export default store;
